# A test utility class to generate id qualifiers.
class Uniquifier
  # Returns a relatively unique integral qualifier. Successive calls to this method
  # within the same time zone spaced more than a millisecond apart return different
  # integers. Each generated qualifier is greater than the previous by an unspecified
  # amount.
  def self.qualifier
    # the first date that this method could be called
    @first ||= Date.new(2010, 01, 01)
    # days as integer + milliseconds as fraction since the first date
    diff = DateTime.now - @first
    # shift a tenth of a milli up into the integer portion
    decimillis = diff * 24 * 60 * 60 * 10000
    # truncate the fraction
    decimillis.truncate
  end
end

class String
  # Returns a relatively unique value obtained from the specified base value.
  # Spaces are removed, e.g.:
  #   Uniquifier.uniquify('Test Name')
  # might produce:
  #   Test_Name_3309388006
  #
  # The suffix is generated by {Uniquifier.qualifier}.
  def uniquify
    gsub(' ', '_') + "_#{Uniquifier.qualifier}"
  end
end