require 'caruby/metadata/propertied'

module CaRuby
  # The metadata persistence mix-in.
  module Metadata
    include Propertied
    
    private
    
    # @param [Property] the property to print
    # @return [<Symbol>] the flags to modify the property
    def pretty_print_attribute_flags(prop)
      flags = super
      flags << :logical if prop.logical?
      flags << :autogenerated if prop.autogenerated?
      flags
    end
    


def self.extend_object(k)
    puts "md def #{k.qp}\n#{caller}" if k.name =~ /BaseHae/
    super
end



    # @return [{String => <Symbol>}] the attributes to print
    def pretty_print_attribute_hash
      puts "car md ppa #{qp} #{ancestors.map { |k| k.name }.qp}...\n#{caller.qp}" if name =~ /BaseHae/
      @@cnt ||= 0 if name =~ /BaseHae/
      @@cnt += 1 if name =~ /BaseHae/
      exit if name =~ /BaseHae/ and @@cnt > 1
      
      super.merge!({
        'creatable domain attributes' => creatable_domain_attributes,
        'updatable domain attributes' => updatable_domain_attributes,
        'fetched domain attributes' => fetched_domain_attributes,
        'cascaded domain attributes' => cascaded_attributes
      })
    end
  end
end
