module CaRuby
  class Database
    # Database CRUD operation.
    class Operation
      attr_reader :type, :subject, :attribute

      # @param [:find, :query, :create, :update, :delete] type the database operation type
      # @param [Persistable] subject the domain object on which the operation is performed
      # @param [{Symbol => Object}, Symbol, nil] the operation characteristics
      # @option opts [Symbol] :attribute the query attribute
      # @option opts [Boolean] :autogenerated whether this is an auto-generated subject update
      def initialize(type, subject, opts=nil)
        @type = type
        @subject = subject
        @attribute = Options.get(:attribute, opts)
        @autogenerated = Options.get(:autogenerated, opts, false)
      end
      
      # @return [Boolean] whether this is a create or update
      def save?
        @type == :create or  @type == :update
      end
      
      # @return [Boolean] whether this operation is an update of an auto-generated subject
      def autogenerated?
        @autogenerated
      end
      
      def to_s
        "#{@subject.qp} #{attribute} #{type}"
      end
    end
  end
end